name: github.com/bobmaertz/railcar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Build application using Make
        run: make build

      - name: Unit Test Coverage Check
        run: |
              echo "Threshold is set at: 80 %"
              cov=$(go tool cover -func=coverage.out | tail -1 | cut -d '     ' -f 11 | cut -d '%' -f 1)
              echo "Current coverage : $cov %"
              if (( 80 < cov)); then
                  echo "OK"
              else
                  echo "Failed"
                  exit 1
              fi
